### ISSUE TITLE
java.lang.NullPointerException at com.github.nkzawa.socketio.client.Manager$6.call

### ISSUE THREAD

**Issue by meidikawardana** [nkzawa/socket.io-client.java#127]
Please help.. version 0.4.2 (newest when I write this issue) ocasionally causing nullPointerException:

the logcat:

03-29 11:33:57.304    1627-1722/com.bei5000.chat W/dalvikvm﹕ threadid=40: thread exiting with uncaught exception (group=0xa4c12648)
03-29 11:33:57.308    1627-1722/com.bei5000.chat E/AndroidRuntime﹕ FATAL EXCEPTION: EventThread
    java.lang.NullPointerException
            at com.github.nkzawa.socketio.client.Manager$6.call(Manager.java:404)
            at com.github.nkzawa.emitter.Emitter.emit(Emitter.java:117)
            at com.github.nkzawa.socketio.client.Socket.access$701(Socket.java:18)
            at com.github.nkzawa.socketio.client.Socket$5.run(Socket.java:166)
            at com.github.nkzawa.thread.EventThread$2.run(EventThread.java:75)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)

I suspect this code is the culprit (I ran this code on my localhost):

//public static String socketUrl = "http://192.168.1.101:8080";

if(GlobalVariables.socket == null){
	try {
		GlobalVariables.socket = IO.socket(GlobalVariables.socketUrl);
	} catch (Exception e) {
		if (BuildConfig.DEBUG)
			Log.e("socket_login_ex",e.toString());
	}
}

try {
	GlobalVariables.socket.emit("disconnect_on_server", new Object());
	GlobalVariables.socket.emit("disconnect", new Object());
	GlobalVariables.socket.emit("connect", new Object());
} catch (Exception e) {
	if (BuildConfig.DEBUG)
		Log.e("login_socket_ex",e.toString());
}

**Comment by sumittops** [comment]
I have also moved to 0.4.2 and have been using it in my project. But honestly I haven't faced this NullPointerException even when I'm offline and not connected to server.

**Comment by naartjie** [comment]
@meidikawardana the problem with `NullPointerException` is because you are trying to use the socket before it's connected. You need to call `socket.connect();` before `socket.emit();`

As an aside, please format your code (see [here](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks)). 

Also using globals is a very bad idea, the author of this library has done a good job of providing an example [project](https://github.com/nkzawa/socket.io-android-chat), please take a look at [`MainFragment.java`](https://github.com/nkzawa/socket.io-android-chat/blob/04704767e1e568b5782c9cc53182af6d63cc528a/app/src/main/java/com/github/nkzawa/socketio/androidchat/MainFragment.java) and how it defines [`mSocket`](https://github.com/nkzawa/socket.io-android-chat/blob/04704767e1e568b5782c9cc53182af6d63cc528a/app/src/main/java/com/github/nkzawa/socketio/androidchat/MainFragment.java#L46) as a member variable.

Good luck.

**Comment by nkzawa** [comment]
Yea, you have to call `connect()` and wait "EVENT_CONNECT" event first.

Thx for your help, @naartjie !

**Comment by meidikawardana** [comment]
thanks @naartjie , I recently updated my app so I use singletons of socket.io. the error never happen again

**Comment by korrio** [comment]
Please share @meidikawardana  your code to the public how you solve this by singletons ?
